config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :messages

  root 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.last(10)
    @message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.js {}
      else
        format.html { render :new }
        format.js { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :sender_id, :receiver_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.slim
.rose
  h1
    ="" 
  span
    =""

app/views/layouts/_footer.html.slim
footer.html.slim

app/views/layouts/_header.html.slim
header.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | One
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .row
      .col-md-2
      .col-md-9
        = yield
    = render 'layouts/footer'

app/views/messages/_form.html.slim
= form_for @message, remote: true do |f|
  .form-group
    = f.text_field :body, class: 'form-control', autocomplete: :off

app/views/messages/_message.html.slim
.tr
  .td
    = message.body

app/views/messages/create.js.erb
$('tbody').append('<%= j render partial: "messages/message", locals: { message: @message } %>');
$('#message_body').val('').focus();

app/views/messages/edit.html.slim
h1
  | Editing Message
= render 'form'
= link_to 'Show', @message
|  | 
= link_to 'Back', messages_path

app/views/messages/index.html.slim
p#notice
  = notice
h1
  | Listing Messages
table
  tbody
    - @messages.each do |message|
      tr
        td
          = message.body
br
 = render 'form'

app/views/messages/new.html.slim
h1
  | New Message
= render 'form'
= link_to 'Back', messages_path

app/views/messages/show.html.slim
p#notice
  = notice
p
  strong
    | Body:
  = @message.body
p
  strong
    | Sender:
  = @message.sender_id
p
  strong
    | Receiver:
  = @message.receiver_id
= link_to 'Edit', edit_message_path(@message)
|  | 
= link_to 'Back', messages_path